import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import AuthWrapper from "./api/lib/auth-wrapper";
import QueryClientProvider from "@/QueryClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthWrapper>
        <body className={inter.className} suppressHydrationWarning>
          <QueryClientProvider>
            <Theme>
              <Navbar />
              <div className="px-5">{children}</div>
            </Theme>
          </QueryClientProvider>
        </body>
      </AuthWrapper>
    </html>
  );
}
